### ISSUE TITLE
Demo page in html instead of php?

### ISSUE THREAD

**Issue by macsupport** [oriongunning/gridder#19]
I can set this up as html but wondering why your demo page needs to be written in php yet your setup etc. illustrates html? Is there a reason you don't have a simple html demo instead of having php?  Just a suggestion.....

**Comment by oriongunning** [comment]
Hello, mostly because I'm lazy. With php, I can use loops, etc.., which makes easy makes it easier to change the markup if needed. 

But you're right, not everybody knows php, so I will definetly add an HTML only version.
