### ISSUE TITLE
Gridder Does Not Initialize in IE9

### ISSUE THREAD

**Issue by moates19** [oriongunning/gridder#20]
My organization uses IE9. Gridder does not start on page load. If you go into the developer tools and refresh it loads without issue.

**Comment by oriongunning** [comment]
Hello moates19,

Does the demo give the same result?
http://www.oriongunning.com/demo/gridder/basic.php

**Comment by moates19** [comment]
It does. All of the demos (php, basic and advanced) work exactly the same. They won't load until you open developer tools and refresh. Very strange.

**Comment by oriongunning** [comment]
Found the problem! Console is not recognized by IE so it throws an error unless the developer tools is opened. Leave 30mins and I'll get a new version pushed!

**Comment by moates19** [comment]
Wow. Great job! I assumed it had something to do with the console.log functions. I removed that from the file but wasn't able to produce the desired result. I'll test it out once it's published and let you know. Thanks!
