### ISSUE TITLE
Looking for words of wisdom!

### ISSUE THREAD

**Issue by TerrySchroeder** [oriongunning/gridder#21]
Great software! After about 7 pots of coffee, I have not been able to get thumbnails (http://codepen.io/srkimir/pen/mGbrf), popover/tooltips (http://www.dynamicdrive.com/dynamicindex5/stickytooltip.htm), or zoom (http://www.jacklmoore.com/zoom/) to work at the gridder-content (carousel level). I did get them all to work at the gridder-list level. Any words of wisdom?

**Comment by oriongunning** [comment]
Using other jQuery plugins in expanded content should work fine. As you can see in my demo, I'm using the bootstrap carousel in the gridder-content level : http://www.oriongunning.com/demo/gridder/basic.php

However, you need to use the onContent callback like this: 

$(".gridder").gridderExpander({
					onContent: function(){
						$(".carousel").thumbnailsCarousel();
					}
                });

Do you see what I mean? 

If this does not make sense, let me know and I'll whip up a demo for you :)

Cheers,
Orion

**Comment by TerrySchroeder** [comment]
Hi Orion,

Thank you for getting back to me!

I grew up on COBOL, soooo, some of this is very new to me. I have been doing most stuff in html and a little jquery.

If you have a chance, I would be most interested in having  zoom ((http://www.jacklmoore.com/zoom/)) integrated into your work of art. If I see how that is done, I think I could take on the ones.

Thank you again,

Terry Schroeder

 

___________________________

              Terry Schroeder

                 611 Vine St.

            Wamego, KS 66547

             636.359.3998 cell

 

        <http://www.thedrywallartist.com/> www.TheDrywallArtist.com

**Comment by oriongunning** [comment]
The advanced demo has a example of how the callbacks work. Check it out. :)
