### ISSUE TITLE
Callback problem

### ISSUE THREAD

**Issue by elemis** [oriongunning/gridder#28]
I haven't been able to make Owl Carousel work in the expanded area. Please check the first thumbnail: http://themes.iki-bir.com/gridder/demo/demo.html Could you help me figure out what is missing? (Owl Carousel works outside of gridder but not inside.)

**Comment by oriongunning** [comment]
Hello Elemis,

You are not using the correct callback, this is the correct one : onContent

Have a good day!

**Comment by oriongunning** [comment]
You will have to destroy the Owl Carousel each time the gridder changes or is closed... Else it will only work for the first one: 
$('owl-carousel').trigger('destroy.owl.carousel');

**Comment by elemis** [comment]
Where should I add destroy? To "onChanged" or "onClosed"?
Will adding exactly this 
$('owl-carousel').trigger('destroy.owl.carousel'); 
be enough?
