### ISSUE TITLE
display:inline-block on ul with 100% width

### ISSUE THREAD

**Issue by jan-dh** [oriongunning/gridder#30]
I had a problem today when trying to implement the plugin with a unorderd list that had a width of 100%. For some strange reason there was always a white border on my divs and the floating element kept pushing away my divs.

One of the solutions is to give the parent element a font-size of 0px and apply a font-size on the list-items.

**Comment by oriongunning** [comment]
Yes, there are a few different solution for removing the space between inline-block items. I usually just ommit the closing </li>, it works like a charm too.
