### ISSUE TITLE
IE Compatibility

### ISSUE THREAD

**Issue by tom8gem** [oriongunning/gridder#32]
This is a nice viewer I'd like to use, however, it doesn't work for me in IE. Is this a known issue, and is there a fix?

**Comment by oriongunning** [comment]
Can you be more specific and tell me which version of IE you use?

**Comment by tom8gem** [comment]
Thank you for replying. I'll need to follow up in a couple days; I'm a Mac user, and the PC I used to access IE was in a public library, closed Sun. & Mon. I'll check in then, but I did have the impression it was a recent version, if not the latest.

I set up a viewer for my own site with Gridder; when I checked in IE, clicking the thumbs had no effect. I thought I may have done something wrong so checked your demo, but the same thing happened there. Has it not been a problem in IE otherwise?

Thanks again!

**Comment by oriongunning** [comment]
There is no reason it should not work in IE. I've tried on IE8 to edge with no problems. Must be something else. Can you press F12 on IE, and tell me if there is any errors in the console?

**Comment by tom8gem** [comment]
Okay thanks, that's reassuring and very good to know. I'll check this as soon as I'm able, tomorrow at the earliest. I'm guessing the library may have taken extra security precautions, since so many people use their computers.

**Comment by tom8gem** [comment]
I checked today in IE9, and see that it works after all. It's odd, though;
it didn't at first, then when I opened the code inspector to check the
console, I was prompted to "refresh the page to see messages that may have
occurred before the F12 tools were opened." Once I refreshed, it worked; I
quit and reopened IE several times and tried again with the same result.
Once F12 tools are engaged, the console shows Log: Gridder Initialized and
Log: Gridder Content Loaded. But it somehow seems to need this extra step…

Thanks again for your help; please pass along any insights or suggestions
you may have.


Thomas Kugler
Graphic & Web Designer
www.thomaskugler.com
tom8gem@gmail.com
(323) 422-6345
