### ISSUE TITLE
Animate change the same as opening a new panel

### ISSUE THREAD

**Issue by joneslafuente** [oriongunning/gridder#34]
A good option would be to animate the closing of the open panel before opening the new one. Is this possible to add myself or does it need an update? I am not a programmer. Also could the open panel be closed by clicking on the body of the page? Apart from these points, excellent code.

Thanks

**Comment by oriongunning** [comment]
Hello. I've tried in the past with no success, as the movement of sliding up and down makes you feel sea sick... And when you click somewhere you expect an instant reaction, not having to wait .5s for the panel to slide down and slide up. It only slides up when you close the panel with close button.

**Comment by oriongunning** [comment]
Adding an clickable overlay beneath the panel is a good idea, i'll look into it for the next version.

**Comment by joneslafuente** [comment]
Thanks. Look forward to the update.

**Comment by joneslafuente** [comment]
I agree with the effect of sliding one closed and then another opening may
not be so great. Thanks.

**Comment by oriongunning** [comment]
After reflexion, the overlay (modal style) does not seem like a good feature as it would cause unwanted closing, etc..
