### ISSUE TITLE
I'm Green Please Forgive Me

### ISSUE THREAD

**Issue by GrantMossman** [oriongunning/gridder#35]
I'm quite new to JS. I am in school for it right now so I'm still learning. I am trying to use the gridder for my portfolio site which is mostly HTML and CSS with just a few JS features. I'm trying to use it in my Portfolio section. It's set up in a 3 element wide grid. Each element in the list is 33.3333% wide and looks just how I want it. 

I have two main issues I cannot solve. First, when I click on the either of the left two list items in each row they cause the rest in the row to bump down to the next row. I cant figure out why. 

And the next problem is after the sixth list item there is a gap created as if there is a invisible 7th list item even though the 7th is in the place where the 8th should go.

If any of this rambling makes sense and you can help that would be awesome.

**Comment by oriongunning** [comment]
Hello, please make sure your css is correct.

.gridder-list {
    display: inline-block;
}

.gridder-show {
    float: left;
    display: block;
}

These styles are mandatory... and making the above a applied correctly, it should solve you first problem.

The other one is weird, I would need to see it in action to debug it, can I view your test online somewhere?

Regards,
Orion

**Comment by GrantMossman** [comment]
https://drive.google.com/folderview?id=0B-06YWl6ldDEdDdIS21OQUVuQTQ&usp=sharing

heres a link to my google drive folder with all my files. The site isn't
live so this is the easiest way to get it to you.

Sorry if its not super organized.

**Comment by oriongunning** [comment]
in you main.css line 132, you need to remove the float:left; that's what's making your first problem.
the other one is due to your images not having the same dimensions. just recrop them at the exact same size in pixel WxH and you will be fine.

**Comment by GrantMossman** [comment]
Got it all solved! 
Thanks!
