### ISSUE TITLE
Possible conflict

### ISSUE THREAD

**Issue by joneslafuente** [oriongunning/gridder#36]
Hi

Using the callback function I have managed to integrate an accordion inside the gridder panel. Works very well. What I now want to be able do is use a jquery function that changes font attributes such as opentype features (kerning) etc. Inside gridder it isn't working but is if I place it outside. 

Is there anything I need to be doing re. callback. Does it need to be inside a callback function within the accordion which is in itself inside the gridder callback. Apologies but I am not a programmer but am helping out a colleague and this is pushing my knowledge rather a bit. At least I am learning something.

Many thanks

Brian

**Comment by oriongunning** [comment]
Hello. Now worries, let see if I can help you. Anything other plugins you wanna launch in the gridder needs to be launch with the onContent callback like this: 
```javascript
$(".gridder").gridderExpander({
    onContent: function(){
        console.log("Gridder Content Loaded");
        $(".carousel").carousel();
     }
});
```
In the case you are trying to attach a jquery click event inside the gridder content, you need to use the on delegation thing, ex:

```javascript
$(".gridder-show").on('click', '.myButtonInsideTheGridderContent', function(){
    console.log('Hello World.');
});
```

**Comment by joneslafuente** [comment]
Hi, Thanks, works perfectly for a button, just need to work out how to use it for drop down menus (select) that then change the css immediately. Have used a change function but not sure if that is what I need. Ideally a select menu with 4 options, each changing the css of a piece of text.

Thanks again

Brian

**Comment by oriongunning** [comment]
If you are trying to do some sort of text editor, why not use a pre-existant one? like this one: http://alex-d.github.io/Trumbowyg/ ??
