### ISSUE TITLE
Content image/text transition

### ISSUE THREAD

**Issue by marioin** [oriongunning/gridder#39]
Thanks for great plugin! 
I would like to fadein .gridder-expanded-content content after click. How can i achieve this?

Thanks!

**Comment by oriongunning** [comment]
Thanks. :)

A fadein will probably be a bit much as it is already expanding vertically. To achieve what you want you can use css : 
.gridder-expanded-content {
    animation-name: fadeIn;
    animation-duration: 1s;
    animation-fill-mode: both;
}

Does that make sense?

**Comment by marioin** [comment]
Hi,

Thanks for quick response :) Actually I have tried css animation before writing to you, but it doesn't work. I have tried to add this line to your basic too, but it also doesn't work :/

**Comment by oriongunning** [comment]
I will work on adding an easier way to deal with animations. I'll close this for now.
