### ISSUE TITLE
Grinder seems to block cmd R refresh shortcut in Chrome (Mac)

### ISSUE THREAD

**Issue by burni** [oriongunning/gridder#40]
I'm testing Gridder on a Wordpress theme I'm building for myself and it appears to block cmd R shortcut on Chrome. If I remove the script enqueue from my functions.php cmd R works again.

I can refresh via the menus and other keybaord shortcuts work. It's such a bizarre issue.

Any ideas?

**Comment by oriongunning** [comment]
Hello. Yes, it does the same for me... I'll have to investigate and fix that burni. Thanks for reporting it.

**Comment by oriongunning** [comment]
Ok, it's because there is a e.preventDefault(), which prevent all key presses... I'll push a new version soon.

**Comment by burni** [comment]
Ah, glad it not just me! Thanks for the quick reply Orion.

And thanks for the plugin - it's really good.
