### ISSUE TITLE
Add items via AJAX

### ISSUE THREAD

**Issue by antonovsky** [oriongunning/gridder#41]
Hello! Thank you for gridder.
There is one problem.
If I add items via ajax, expanding do not work for this items.
I think it's because gridder initialized only once and can not be changed.
`            /* CLICK EVENT */
            _this.find(".gridder-list").on("click", function (e) {
                e.preventDefault();
                var myself = $(this);
                openExpander(myself);
            });`
This code is not called for added via ajax items.
Please help me.
Sorry for my English, I write through google translate.

**Comment by oriongunning** [comment]
Hello. Thanks for reporting. I never had that scenario. I'll looking into it.

**Comment by oriongunning** [comment]
The new version should work now for you. :)

**Comment by antonovsky** [comment]
Thank you very much!
