### ISSUE TITLE
Bug first time the page runs

### ISSUE THREAD

**Issue by mamadetin** [oriongunning/gridder#53]
Hi, in all the browsers the first time you access to the page it looks like that, with no spaces. 
And if you reload again its ok again.
Can you help me? please

![screen shot 2017-03-17 at 10 02 55 am](https://cloud.githubusercontent.com/assets/26485967/24046436/e83ff708-0af8-11e7-985c-3afe1b6554d8.png)

![screen shot 2017-03-17 at 10 04 14 am](https://cloud.githubusercontent.com/assets/26485967/24046490/19ecf6f2-0af9-11e7-9eb5-2e69d1ed9898.png)

**Comment by oriongunning** [comment]
It seems to be resolved. Are you still having issues?
