### ISSUE TITLE
Expander at wrong place

### ISSUE THREAD

**Issue by ZeAntwan** [oriongunning/gridder#55]
Hi !
First of all, thanks for this **GREAT** plugin. I've been trying to do this in jQuery, and couldn't seem to do it...

Secondly, I know my issue has been solved  (#43) , but the solution doesn't seem to work on my end...

The expander is at the right place in the code but it breaks the grid...
I tried some "float" hack here and there but can't get it to work...
Here is the website : [dev.antoinesarrazin.com](http://dev.antoinesarrazin.com)
(Go down to the portfolio and click on one of the first two items)

I'm using Pure CSS as a framework, but even stripping it down to CSS Media queries I can't get it to work.

If you have a solution, that would be awesome !

**Comment by oriongunning** [comment]
Hello. The problem is you have display: flex on the parent container. (section#portfolio). If you remove that, it'll work. They may be a way to tweak the css to it work with flexbox. Cheers, Orion.

**Comment by ZeAntwan** [comment]
**YES ! IT WORKS ! FINALLY !**
That was the first feature I wanted to get for my website and FINALLY IT WORKS thanks to your plugin and your great help !

Thanks a LOT !
