### ISSUE TITLE
gridder by default first open preview

### ISSUE THREAD

**Issue by vish9833** [oriongunning/gridder#58]
Hi,
How can i do this function..

**Comment by oriongunning** [comment]
You can do something like:
``
$(".gridder").gridderExpander({
        // other options
        onStart: function () {
            // You can manually specifiy one like this.
            jQuery('.gridder .gridder-list:nth-child(1)').trigger('click');
            // OR
            // You can open the relevant one via a hash in the url
            index_position = document.URL.indexOf("#");
            if(index_position != -1) {
               anchor_name = document.URL.substring(index_position);
               $(anchor_name).trigger("click");
            }
        },
    });
``

**Comment by vish9833** [comment]
Thank you!
