### ISSUE TITLE
Not visible on mobile

### ISSUE THREAD

**Issue by mtsweir** [oriongunning/gridder#61]
A few issues here, when I preview the demo in Chrome Dev Tools, there is just white space where the grid should appear. What the issue could be is that you override the height of ".gridder-list .image" to auto which essentially removes all heights, if I remove the auto height it then shows the grid.

Another issue is when the one grid element is expanded the content doesn't expand fully and overlaps any grid elements below. I added a min-height to the ".gridder-show" div so I could a least set a manual height, but in the real world, this will always vary.

![screen shot 2018-01-13 at 9 26 09 am](https://user-images.githubusercontent.com/4976660/34894095-e40c0570-f844-11e7-9c15-18ee742b552a.jpg)

![Uploading Screen Shot 2018-01-13 at 9.22.10 AM.jpg…]()

**Comment by jordan-webdev** [comment]
I am wondering, too, if there is a solution to this. Ideally, this has to be mobile-friendly in order for me to use it on any responsive site. mtsweir, did you come up with any other solution?

**Comment by oriongunning** [comment]
You need to update the CSS to cater your needs. 
In this example http://oriongunning.github.io/gridder/ , you will see that the expanded content displays correctly.

**Comment by mtsweir** [comment]
I grabbed the latest from this repo and previewed in Chrome (64)
This is what I am seeing...

![screen shot 2018-01-31 at 7 56 55 pm](https://user-images.githubusercontent.com/4976660/35609146-1578dc8e-06c1-11e8-9d64-76d81b15c6be.jpg)

While it kind of works, I need to do many fixes (css resets, style tweaks) just to get it stable.

The http://oriongunning.github.io/gridder/ demo example seems more complete, should I be using this or the Github version?

**Comment by oriongunning** [comment]
The demo has been updated a little to show you how to achieve responsive.. Basically, I only provide the strict minimun CSS for GRIDDER to work. If you want it to responsive, you can achieve that very easily with media queries but it is outside of the scope of GRIDDER.

**Comment by mtsweir** [comment]
Cheers for following this up.
