### ISSUE TITLE
Not working with jQuery v3.2.1

### ISSUE THREAD

**Issue by mtsweir** [oriongunning/gridder#62]
I'm using this on a Bootstrap v4.0 project and getting errors in the console, see attached.

![screen shot 2018-01-13 at 6 05 46 pm](https://user-images.githubusercontent.com/4976660/34903000-7414f716-f88c-11e7-95d1-8c2b8d2ed536.jpg)

**Comment by oriongunning** [comment]
This is due to using the "slim" version for jQuery which does not have any of the effects function. Solution, use the full version of jquery.
