### ISSUE TITLE
Flexbox breaking grid

### ISSUE THREAD

**Issue by KyleShook** [oriongunning/gridder#72]
When I add display: flex; to my CSS for .gridder to center & space my grid, upon opening each grid item the other items are shifted down a row.

So if I click the first item, it shifts the others on the same row down below the expanded part and if I click the ones below the expanded section they move back up to the first row as I click them.

**Comment by oriongunning** [comment]
This will not work with flexbox.

FIY, all the .gridder-list should be display: inline-block; and the gridder-show should be display block;float:left;
