### ISSUE TITLE
"deeplinking"

### ISSUE THREAD

**Issue by vespino** [oriongunning/gridder#9]
Is it possible to show a certain block when opening the page? I have tried jQuery trigger, but this doesn't seem to do the trick.

**Comment by oriongunning** [comment]
It should do the trick. (can you send a link? so I can debug it?)

I do not want to add "real" deeplinking as I really want to keep this plugin simple and easy for anybody to use.

I've done another more advanced version that does deeplinking. It does however requires you to feed it data via ajax.

check it out : http://www.oriongunning.com/demo/gridder-ajax/demo.php?item=item-006000

GITHUB : https://github.com/oriongunning/gridder-ajax

**Comment by oriongunning** [comment]
I've made an example of how to achieve deep linking with the basic GRIDDER : http://codepen.io/anon/pen/MYJLGP

**Comment by vespino** [comment]
Thank you.
